### ISSUE TITLE
Problems after editing the blender file

### ISSUE THREAD

**Issue by Kunstbanause** [lambertjamesd/n64brew2023#4]
After editing the level in blender I get a _doppler effect_ when running the rom in an emulator or original n64 hardware with an everdrive:
![doppler](https://github.com/lambertjamesd/n64brew2023/assets/3209654/b9a1cf67-0e69-4695-bf5e-c073c82a7a71)

Does anyone have an idea what I am doing wrong in my modelling: 
![grafik](https://github.com/lambertjamesd/n64brew2023/assets/3209654/093b6db6-1f66-4191-b588-916203adbd35)

**Comment by Kunstbanause** [comment]
Does it have to do with the following sentence from the readme?
> The geometry for a single mega texture must also be flat

I tried a square room and that also did not work well
![grafik](https://github.com/lambertjamesd/n64brew2023/assets/3209654/05f3000a-d602-4979-a57f-e0df7af7f36f)
I can't seem to figure out what is wrong :/

**Comment by lambertjamesd** [comment]
You can break the curved mesh into a bunch of individual meshes and that will still work

**Comment by Kunstbanause** [comment]
Cheers, I'll give it a try!

**Comment by Kunstbanause** [comment]
Thanks, I understood now. The _flat geometry_ - which I have not adhered to - was certainly the issue. Sorry to have wasted your time 🙏🏻

A couple of superstitious steps I took, but did not have the time to evaluate for sure:
* You need to be inside the geometry, no where should there be holes in the geometry where the camera looks into the void
* After editing an object in blender, the dimension can get confused: X=0.000001 as in the example below does not work and should be corrected to 0
![grafik](https://github.com/lambertjamesd/n64brew2023/assets/3209654/b5aa9b13-6e8b-4d98-8e27-d7429ecc4921)
